#!/bin/bash

mkdir -p ../src/antlr
rm ../src/antlr/*

java -jar antlr-4.9.3-complete.jar ../grammar/AritmeticLexer.g4
java -jar antlr-4.9.3-complete.jar -visitor ../grammar/AritmeticParser.g4

mv ../grammar/* ../src/antlr
mv ../src/antlr/*.g4 ../grammar

